apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: autonomous-agent-production
  namespace: autonomous-agent

# Base configuration
resources:
  - ../../base
  - ingress.yaml
  - backup-cronjob.yaml
  - security-scanner.yaml

# Environment-specific labels
commonLabels:
  environment: production
  deployment: stable

# Environment-specific annotations
commonAnnotations:
  deployment.kubernetes.io/environment: production
  deployment.kubernetes.io/tier: production

# Production-specific patches
patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "production"

  - target:
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"

  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "2Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"

  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "8Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "4000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "16Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "8000m"

  - target:
      kind: HorizontalPodAutoscaler
      name: app-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 20
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
      - op: replace
        path: /spec/metrics/1/resource/target/averageUtilization
        value: 70

  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "100Gi"

  - target:
      kind: PersistentVolumeClaim
      name: app-data-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "100Gi"

  - target:
      kind: PersistentVolumeClaim
      name: ollama-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "200Gi"

# Production images
images:
  - name: autonomous-agent
    newTag: v1.0.0-production
  - name: postgres
    newTag: 15-alpine
  - name: redis
    newTag: 7-alpine
  - name: ollama/ollama
    newTag: latest
  - name: nginx
    newTag: alpine
  - name: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newTag: latest

# Configuration generators
configMapGenerator:
  - name: production-config
    literals:
      - environment=production
      - log_level=INFO
      - debug=false
      - metrics_enabled=true
      - monitoring_enabled=true
      - backup_enabled=true
      - security_scan_enabled=true

# Secret generators
secretGenerator:
  - name: production-secrets
    literals:
      - backup.encryption.key=CHANGE_ME_PRODUCTION_BACKUP_KEY
      - monitoring.auth.token=CHANGE_ME_PRODUCTION_MONITORING_TOKEN

# Namespace
namespace: autonomous-agent

# Replica configuration
replicas:
  - name: app
    count: 5
  - name: nginx
    count: 3
  - name: postgres
    count: 1
  - name: redis
    count: 1
  - name: ollama
    count: 1
  - name: prometheus
    count: 1
  - name: grafana
    count: 1