name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.6.1'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Update dependencies
      run: |
        poetry update
        poetry show --outdated
        
    - name: Run tests with updated dependencies
      env:
        TESTING: true
        DISABLE_EXTERNAL_APIS: true
      run: |
        poetry install --no-interaction
        poetry run pytest tests/ \
          --cov=src \
          --cov-fail-under=90 \
          --tb=short \
          -v \
          --maxfail=5
          
    - name: Check for security vulnerabilities
      run: |
        poetry run safety check
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          This is an automated pull request to update project dependencies.
          
          ## Changes
          - Updated all dependencies to their latest compatible versions
          - Ran full test suite to ensure compatibility
          - Verified no security vulnerabilities
          
          ## Testing
          - ✅ Unit tests pass
          - ✅ Integration tests pass
          - ✅ Security scan clean
          - ✅ Linting passes
          
          Please review the changes and merge if everything looks good.
        branch: dependency-updates
        delete-branch: true
        draft: false